"""Post-run reproducibility inventory and recorded branch decisions only."""
import sys,json,time,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from scripts.vera_stage8_common import OUT,write,sha,protected,evaluator_guard

def main():
 evaluator_guard();previous=protected();b=json.loads((OUT/'step1/branch.json').read_text())
 write(OUT/'branch_decisions.json',{'step2':'not run: prescribed initial PROB 50±3 gate','step3':'not run: prescribed initial PROB 50±3 gate','step1':b,'step4':'executed after hybrid inference as fixed 2/4/10 s diagnostic; no best-window selection','fps':'unverified; no raw containers available; retain 30 FPS assumption','holdout':'user explicitly approved exploratory only and deferred confirmation','seed_correction':'initial Step4 attempt interrupted before labels and retained in diagnostics; canonical Step4 explicitly seeded; all Step5 validation and explanation calls replayed with seed0 and required exact equality'})
 sources={str(p.relative_to(ROOT)):sha(p) for p in (ROOT/'scripts').glob('*stage8*.py')};sources.update({str(p.relative_to(ROOT)):sha(p) for p in (ROOT/'tests').glob('*stage8*.py')})
 write(OUT/'source_inventory.json',{'files':sources,'evaluator_original_lock':json.loads((OUT/'evaluator_lock.json').read_text()),'model_inventory':'step1/model_verification.json','split_sha256':sha(ROOT/'experiments/stage2_1/split.json')})
 write(OUT/'previous_protection_verification.json',{'status':'passed','files':previous,'R01_R02_R03_stage4_artifacts':'unchanged','prior_stages_1_to_7':'unchanged','checked_at':time.time()})
 write(OUT/'reproduction_commands.json',{'python':'/home/jeong/Desktop/IPAD/cache/vera/venv/bin/python','working_directory':str(ROOT),'commands':['scripts/run_vera_stage8_sanity.py','scripts/run_vera_stage8_prob.py --phase preflight','scripts/run_vera_stage8_prob.py --phase evaluation','scripts/analyze_vera_stage8.py --step step0','scripts/analyze_vera_stage8.py --step step1','scripts/prepare_vera_stage8_dino.py','scripts/run_vera_stage8_dino.py','scripts/with_vera_seed0.py scripts/run_vera_stage8_hybrid.py','scripts/with_vera_seed0.py scripts/explain_vera_stage8.py','scripts/run_vera_stage8_windows.py','scripts/bootstrap_vera_stage8_parallel.py --step step5','scripts/bootstrap_vera_stage8_parallel.py --step step4','scripts/analyze_vera_stage8_followup.py --step step5','scripts/analyze_vera_stage8_followup.py --step step4','scripts/verify_vera_stage8.py --step step0','scripts/verify_vera_stage8.py --step step1','scripts/verify_vera_stage8_followup.py --step step5','scripts/verify_vera_stage8_followup.py --step step4'],'logging':'wrap each command using scripts/logged_command.py --stage stage8 --step NAME -- PYTHON COMMAND','local_assets':'original IPAD frames, pinned InternVL2/ImageBind/DINOv2 weights; images/weights/cache never published','fresh_reproduction':'Start with previous-stage assets and an empty stage8 output directory in a separate copy; preserve canonical outputs. Frozen source hashes reject divergent code.'})
 print('Source and prior-protection inventories recorded.')
if __name__=='__main__':main()
