"""Add only completed, verified experiment stages to the Korean public record."""
import argparse,json
from pathlib import Path
ROOT=Path.cwd()
def main():
 p=argparse.ArgumentParser();p.add_argument('stage',choices=['stage2_2','stage2_3','stage3']);a=p.parse_args()
 out=ROOT/'experiments'/a.stage;status=json.loads((out/'status.json').read_text());assert status['status']=='complete'
 registry_path=ROOT/'experiments/stages.json';registry=json.loads(registry_path.read_text());readme=ROOT/'README.md';text=readme.read_text()
 if a.stage in registry:raise RuntimeError('Stage already reported; preserve evidence and update explicitly')
 if a.stage=='stage2_2':
  summary=json.loads((out/'training_summary.json').read_text());assert summary['status']=='passed'
  text=text.replace('질문 최적화 전체나 원 논문 벤치마크 수치의 재현을 의미하지 않는다.', '1단계는 공개 질문 전이 평가이고 2-2단계의 질문 학습은 별도 기록했다. 원 논문 벤치마크 수치 재현을 의미하지 않는다.')
  title='learner–optimizer 반복 질문 최적화';row=f"| **2-2** | **{title}** | **완료** | 10 epoch·600 반복, 유효 optimizer {summary['valid_optimizer_updates']}회, 형식 오류 {summary['invalid_optimizer_total']}회 |"
  body=f'''\n## 2-2단계 — learner–optimizer 반복 질문 최적화 (완료)\n\nIPAD 학습 120개 영상에 대해 **10 epoch, 배치 2, 총 600회** 질문 업데이트를 수행했다. 모델 가중치는 동결된 InternVL2-8B BF16이며, 동일 모델이 learner와 optimizer 역할을 순차적으로 수행했다. 원 논문의 수동 초기 질문 2개(Q0)에서 시작했으며 공개 UCF 학습 질문으로 시작하지 않았다. 각 영상 전체에서 `i × floor(F/8)`로 선택한 8프레임을 learner에 전달했다. Optimizer에는 두 영상의 16프레임, learner 예측 두 개, 학습용 비디오 라벨 두 개, 현재 질문을 전달했다. 프레임별 이상 위치는 입력하지 않았다.\n\n생성은 `do_sample=False`, `num_beams=1`, `max_new_tokens=1024`, seed 0으로 고정했다. Q0와 100회마다 생성된 질문을 검증 17개 영상으로 평가했다. **모델 파라미터 업데이트는 0회**이며 학습된 것은 질문 텍스트다.\n\n- 반영된 learner 예측: **1,200개**, 실제 learner 호출: **{summary['learner_attempts']}회**(미완료 시도 {summary['uncommitted_learner_attempts']}회 포함), optimizer 호출: **600회**, 검증 호출: **119회**.\n- 유효 optimizer 응답: **{summary['valid_optimizer_updates']}회**, 형식 오류로 이전 질문 유지: **{summary['invalid_optimizer_total']}회**, 실제 질문 문자열 변경: **{summary['questions_changed']}회**.\n- 출력은 최대 5개의 완결된 번호 질문으로 검사했다. **공식 코드의 앞 5줄 자르기와 달리**, 초과 질문·불완전 형식은 수정하거나 임의로 잘라 쓰지 않고 이전 질문을 유지했다. 이 구현 차이와 모든 원문/오류를 남겼다.\n- 균등 8프레임에 이상 프레임이 없는 학습 이상 영상은 35개 중 1개였고, 검증 이상 영상 6개는 모두 이상 프레임을 포함했다. [샘플링 점검](experiments/stage2_2/sampling_label_diagnostic.json)은 기술 통계이며 샘플링 변경이나 질문 입력에 사용하지 않았다.\n- 최초 실행은 환경 기록 단계에서 `pip` 모듈 부재로 실패했다. 학습 시작 전 표준 패키지 메타데이터 조회로 수정했으며, 이전 소스·설정·실패 로그는 `startup_failures/001`에 보존했다.\n- 186회 시작 시 learner가 같은 줄 끝에 명시적 `Output: 0`을 반환했지만 기존 줄 시작 파서가 거부해 중단됐다. 마지막 명시적 이진 Output을 줄 위치와 무관하게 읽도록 수정하고, 이전 성공 응답 404개의 판정이 모두 같음을 확인한 뒤 185회 완료 지점에서 재개했다. 모델·질문·분할·생성 예산은 변경하지 않았다. [수정·재개 근거](experiments/stage2_2/revisions/001_inline_output_fix/verification.json).\n- 218회 시작 시에는 이진 Output 뒤에 결론 문장이 붙어 중단됐다. 유일한 명시적 이진 Output 필드를 읽고 모호한 값은 거부하도록 보강했으며, 이전 성공 판정 485개가 같음을 확인하고 217회 완료 지점에서 재개했다. [두 번째 수정 근거](experiments/stage2_2/revisions/002_scalar_output_field/verification.json).\n- 관련 회귀 테스트 **37개 통과**, 첫 파서 보강 **12개 통과**, 두 번째 보강 **18개 통과**, 최종 전체 회귀 **48개 통과**, 실제 모델 파일 22개 SHA256 일치, 모든 반복·배치·응답·검증의 독립 재검산 통과.\n\n| 검증 시점 (업데이트 수) | 정답 / 17 | 검증 정확도 | TP | FP | TN | FN |\n|---|---:|---:|---:|---:|---:|---:|\n'''
  for r in summary['validation']:body+=f"| {r['step']} | {r['correct']} / {r['total']} | {100*r['accuracy']:.2f}% | {r['tp']} | {r['fp']} | {r['tn']} | {r['fn']} |\n"
  body+='''\nTP/FP/TN/FN은 이상 탐지 기준의 참양성/거짓양성/참음성/거짓음성이다. 검증 정상 영상이 11/17이므로 모두 정상으로 판정해도 정확도는 64.71%이며, 이 기준선과 함께 해석한다.\n\n호출별 VLM 시간은 이미지 전처리·GPU 전송 이후의 `model.chat` 구간이다. 전체 실행 시간은 각 command.json에 따로 기록했으며, reserved VRAM은 같은 프로세스의 이전 호출 캐시를 포함한다.\n\n학습 배치 정확도는 반복마다 질문이 바뀌는 online 통계이므로 고정된 모델의 평가 정확도로 해석하지 않는다. 검증은 질문 선택용이며 최종 평가 영상은 학습·검증 입력에서 제외했다.\n\n근거: [고정 설정·배치 순서](experiments/stage2_2/frozen.json), [전체 반복 이력](experiments/stage2_2/iterations.jsonl), [반복별 CSV](experiments/stage2_2/history.csv), [질문 버전 목록](experiments/stage2_2/questions_catalog.json), [learner 원문](experiments/stage2_2/learner_responses.jsonl), [optimizer 원문](experiments/stage2_2/optimizer_responses.jsonl), [검증 결과](experiments/stage2_2/validation), [학습 요약·검산](experiments/stage2_2/training_summary.json), [실행 로그](experiments/stage2_2/execution), [실패 기록](experiments/stage2_2/failures.jsonl).\n'''
 elif a.stage=='stage2_3':
  result=json.loads((out/'selection.json').read_text());r=result['selected'];title='검증 정확도에 따른 질문 선택'
  row=f"| **2-3** | **{title}** | **완료** | 업데이트 {r['step']}의 질문 선택, 검증 {r['correct']}/{r['total']} ({100*r['accuracy']:.2f}%) |"
  body=f'''\n## 2-3단계 — 질문 선택 (완료)\n\nQ0 및 100·200·300·400·500·600회 업데이트의 7개 후보를 **동일한 검증 17개 영상의 비디오 분류 정확도**로 비교했다. 사전에 고정한 규칙대로 정확도가 가장 높은 후보를 선택했고, 동률은 가장 이른 후보를 유지했다. 최종 평가 프레임 라벨이나 AUROC는 선택에 사용하지 않았다.\n\n선택 결과는 **업데이트 {r['step']}의 질문**, 검증 정확도 **{r['correct']}/{r['total']} = {100*r['accuracy']:.2f}%**이다. {'초기 Q0가 선택되었으므로 optimizer가 생성한 질문이 최종 선택됐다고 표현하지 않는다.' if r['step']==0 else 'Optimizer가 생성한 질문이 선택되었다.'} 선택 후보의 검증 혼동행렬은 TP={r['confusion']['tp']}, FP={r['confusion']['fp']}, TN={r['confusion']['tn']}, FN={r['confusion']['fn']}이다. 검증 표본이 17개로 작아 선택 결과의 불확실성이 크다.\n\n선택한 원문은 다음과 같다.\n\n```text\n{r['questions'].rstrip()}\n```\n\n[선택 이력과 후보](experiments/stage2_3/selection.json), [동결 질문](experiments/stage2_3/questions.txt), [완료·해시](experiments/stage2_3/status.json), [실행 로그](experiments/stage2_3/execution). 질문 SHA256을 고정했다.\n'''
 else:
  metrics=json.loads((out/'metrics.json').read_text());verification=json.loads((out/'independent_verification.json').read_text());assert verification['status']=='passed'
  comparison=json.loads((out/'stage1_common_support.json').read_text());counts=json.loads((out/'raw_prediction_counts.json').read_text());final=metrics['final'];title='선택 질문의 IPAD 재분할 평가'
  row=f"| **3** | **{title}** | **완료** | {status['videos']}개 영상·{status['frames']:,}프레임, macro AUROC {final['macro']['auroc']:.2f}% / AP {final['macro']['auprc']:.2f}% |"
  body=f'''\n## 3단계 — IPAD 재분할 평가 (완료)\n\n동결된 선택 질문을 학습·질문 선택에서 제외한 **{status['videos']}개 IPAD 영상, {status['frames']:,}프레임**에 적용했다. 추가 데이터셋은 사용하지 않았다. 구간 간격 16프레임, 30 FPS 가정의 10초 창에서 8프레임, ImageBind FP32 검색, 논문 기준 Gaussian smoothing과 위치 가중치는 1단계와 동일하다. ImageBind 특징은 평가 영상 전체에서 다시 계산했다. 프레임 라벨은 VLM·특징 추출이 모두 끝난 뒤 평가기에만 전달했다.\n\n| 점수 단계 | macro AUROC | macro AP | pooled AUROC | pooled AP |\n|---|---:|---:|---:|---:|\n'''
  for name,label in [('initial','초기 이진 판정'),('retrieved','장면 문맥 검색'),('smoothed','Gaussian smoothing'),('final','최종 위치 가중치')]:
   m=metrics[name];body+=f"| {label} | {m['macro']['auroc']:.2f} | {m['macro']['auprc']:.2f} | {m['pooled']['auroc']:.2f} | {m['pooled']['auprc']:.2f} |\n"
  body+='\n단위는 %. macro는 4개 장면의 단순 평균이며 AP는 average precision이다.\n\n| 장면 | 영상 수 | 프레임 수 | 이상 판정 구간 / 전체 | 최종 AUROC | 최종 AP |\n|---|---:|---:|---:|---:|---:|\n'
  for scene,m in final['scenes'].items():
   rs=[v for k,v in counts.items() if k.startswith(scene+'/')];body+=f"| {scene} | {len(rs)} | {m['frames']:,} | {sum(r['positive_segments'] for r in rs)} / {sum(r['segments'] for r in rs)} | {m['auroc']:.2f} | {m['auprc']:.2f} |\n"
  body+=f"\n### 1단계와 동일 프레임 비교\n\n전체 평가 분할이 바뀌었으므로 1단계의 전체 63개 영상 지표와 직접 차이를 계산하지 않는다. 기존 testing 중 새 분할에서도 평가로 남은 **{comparison['videos']}개 영상·{comparison['frames']:,}프레임**에서만 1단계와 동일 범위로 다시 비교했다.\n\n| 질문 | 공통 범위 macro AUROC | 공통 범위 macro AP |\n|---|---:|---:|\n"
  for key,label in [('stage1_public_UCF_questions','1단계 공개 UCF 질문'),('stage3_selected_questions','이번 선택 질문')]:
   m=comparison[key]['macro'];body+=f"| {label} | {m['auroc']:.2f} | {m['auprc']:.2f} |\n"
  body+='''\n새 평가 영상에는 기존 정상 training에서 분리한 영상도 포함되어 있다. 기존 testing은 1단계에서 이미 관찰했으며 촬영 세션 단위 분리도 확인할 수 없으므로, 이 결과는 **IPAD 재분할 탐색적 평가**다. 원 논문 UCF/XD 성능이나 표준 IPAD 테스트셋 성능의 재현으로 표현하지 않는다. 모든 추론은 미래·전체 영상 문맥을 사용하는 오프라인 방식이다. VLM 시간은 전처리 이후 `model.chat`, ImageBind 시간은 자체 전처리를 포함한 `encode` 구간이며 모델 로딩·입력 해시 검사·로그 쓰기는 별도다. 전체 벽시계 시간은 실행 command.json에 보존했다.\n\n근거: [고정 질문·설정·소스](experiments/stage3/frozen.json), [실제 모델 파일 해시 검증](experiments/stage3/model_verification.json), [프레임 점수](experiments/stage3/frame_scores.csv), [전체 지표](experiments/stage3/metrics.json), [동일 범위 비교](experiments/stage3/stage1_common_support.json), [원문 설명](experiments/stage3/inference), [후처리](experiments/stage3/postprocessing), [처리시간·VRAM](experiments/stage3/runtime_summary.json), [독립 검산](experiments/stage3/independent_verification.json), [실행 로그](experiments/stage3/execution). 특징 벡터와 이미지·모델은 로컬 보존, SHA256과 프레임 ID만 공개했다.\n'''
  text=text.replace('**1단계: VERA 논문 추론 방법론 재현 완료.**',f"**최신 완료: 3단계 IPAD 재분할 평가 — macro AUROC {final['macro']['auroc']:.2f}%, AP {final['macro']['auprc']:.2f}%.** 전체 37개 평가 영상 기준이며, 아래 1단계와 평가 범위가 다르다.\n\n**1단계: VERA 논문 추론 방법론 재현 완료.**")
 # Insert into existing executed-stage table only now, after successful verification.
 position=text.index('\n\n진행 상태는');text=text[:position]+'\n'+row+text[position:];text+=body;readme.write_text(text)
 registry[a.stage]={'title':title,'status':'complete','execution_approved':True,'status_file':str((out/'status.json').relative_to(ROOT)),'artifact_directory':str(out.relative_to(ROOT))};registry_path.write_text(json.dumps(registry,ensure_ascii=False,indent=2)+'\n')
 print('Reported completed stage:',a.stage)
if __name__=='__main__':main()
