"""Publish only completed, audited scene-specific stage4 evidence to the Korean README."""
import argparse,json,re
from pathlib import Path
ROOT=Path.cwd()
def main(scene,kind):
 out=ROOT/'experiments/stage4'/scene/kind;status=json.loads((out/'status.json').read_text());audit=json.loads((out/'independent_verification.json').read_text());assert status['status']=='complete' and audit['status']=='passed'
 registry_path=ROOT/'experiments/stages.json';registry=json.loads(registry_path.read_text());key=f'stage4_{scene}_{kind}'
 if key in registry:print('Already reported:',key);return
 path=ROOT/'README.md';text=path.read_text();prefix=f'experiments/stage4/{scene}/{kind}'
 if kind=='normal':
  profile=json.loads((out/'normal_profile.json').read_text());rules=json.loads((out/'rules.json').read_text());title=f'4단계 {scene} 정상 기준 생성·점검'
  row=f"| **4-{scene}-N** | **{scene} 정상 기준·질문 생성** | **완료** | 생성 {status['generation_videos']}개 / 점검 {status['audit_videos']}개 정상 영상, 규칙 {status['accepted_rules']}/{status['candidate_rules']}개 채택 |"
  body=f'''\n## 4단계 {scene} — 정상 기준 생성·점검 (완료)\n\n해당 장면의 학습 정상 영상만 사용했다. 정렬한 영상 ID를 장면별 seed 0으로 섞고 20%를 올림하여 내부 점검용으로 분리했다. **생성 {status['generation_videos']}개, 점검 {status['audit_videos']}개**이며 다른 장면·학습 이상·검증·평가 영상은 정상 설명 생성에 사용하지 않았다.\n\n기존 16프레임 간격·10초 창·8프레임 입력으로 생성 영상의 **{audit['observed_segments']}개 구간**을 관찰했다. 영상별 요약에서 최대 5개 조건부 정상 규칙과 질문을 생성했다. 각 규칙에 인용된 서로 다른 정상 영상 3개 이상의 구간을 다시 시각적으로 확인하고, 내부 정상 점검 영상의 전체 창에서 명확한 반례가 있으면 필수 기준에서 제외했다. 정확한 공정 시간이나 관찰되지 않은 필수 순서는 만들지 않았다.\n\n**후보 {status['candidate_rules']}개 중 {status['accepted_rules']}개 채택**, 정상 설명 {status['normal_tokens']}토큰(상한 1,024)이다. 규칙 검증은 같은 동결 VLM의 판단이며 사람의 독립 정답 주석이 아니다. 영상 인용·프레임 정렬·규칙 채택 조건은 별도 코드로 재검산했다. 모델 가중치 업데이트와 learner–optimizer 질문 반복은 수행하지 않았다. JSON 형식 오류는 원문을 보존하고 최대 2회 형식 복구만 허용했으며 성능을 보고 후보를 다시 선택하지 않았다.\n\n| 규칙 | 생성 근거 영상 수 | 정상 점검 반례 구간 수 | 채택 |\n|---|---:|---:|---|\n'''
  for r in rules:body+=f"| {r['id']} | {r['supported_generation_videos']} | {len(r['audit_contradictions'])} | {'예' if r['accepted'] else '아니오'} |\n"
  if (out/'revisions/001_summary_cardinality/verification.json').exists():body+=f'\n실행 중 영상 요약이 6개 요청을 초과해 구간별 관찰을 나열하면서 중단됐다. 원문·2회 형식 복구 실패·이전 소스를 보존하고, 유효한 중간 요약을 버리지 않도록 항목 수 검사만 해당 영상 구간 수까지 허용했다. 기존 298개 관찰 구간과 19개 성공 요약은 그대로 유지했다. 최종 규칙·설명 토큰·질문 상한, 모델·입력·분할·생성 설정은 바꾸지 않았다. [수정·재개 검증]({prefix}/revisions/001_summary_cardinality/verification.json).\n'
  if (out/'revisions/002_citation_feedback/verification.json').exists():body+=f'\n후보 생성에서는 요약에 없는 구간 번호를 인용해 중단됐다. 빈 AssertionError 대신 실제 허용된 근거 위치를 형식 복구에 전달하도록 오류 메시지를 보완했다. 인용 허용 조건은 유지했고 정상 관찰·분할·모델·생성 설정은 변경하지 않았다. [인용 검사 수정 기록]({prefix}/revisions/002_citation_feedback/verification.json).\n'
  if (out/'revisions/003_cumulative_format_repair/verification.json').exists():body+=f'\n인용 형식 복구가 최초 응답으로 되돌아가던 실행기 오류를 수정하여 직전 수정본을 누적 사용하고 모든 잘못된 인용을 함께 알리도록 했다. 회귀 테스트 10개가 통과했다. 328개 관찰·22개 요약은 재추론 없이 보존했다. [복구 로직 수정·검증]({prefix}/revisions/003_cumulative_format_repair/verification.json), [실패 원문]({prefix}/failures.jsonl).\n'
  if (out/'revisions/004_reject_invalid_candidates/verification.json').exists():body+=f'\n형식 복구 후에도 남은 잘못된 인용은 후보별로 제외했다. 근거 위치를 임의 대체하지 않고 유효한 후보에만 시각적 근거 검사를 수행했다. 후보 제외 회귀를 포함한 테스트 11개가 통과했다. [후보 제외·재개 기록]({prefix}/revisions/004_reject_invalid_candidates/verification.json), [잘못된 인용 후보]({prefix}/invalid_candidates.json).\n'
  if (out/'revisions/005_compact_visual_checks/verification.json').exists():body+=f'\n시각적 근거 JSON에서 모델이 프레임 번호를 수백 개 나열하다 잘리는 문제가 발생했다. 실행기가 원본 frame ID를 이미 보존하므로 검사 출력은 규칙 ID·지지/반례/관찰 불가·짧은 근거의 한 줄 형식으로 바꾸고 기존 검사 시도를 별도 보존했다. 파싱 실패는 관찰 불가나 정상으로 치환하지 않으며, 내부 점검 실패가 남은 규칙도 제외했다. 관련 테스트 12개 통과. [검사 형식 변경 기록]({prefix}/revisions/005_compact_visual_checks/verification.json).\n'
  if (out/'revisions/006_scalar_visual_verdict/verification.json').exists():body+=f'\n모델이 설명 없이 명확한 한 단어 판정을 반환하는 경우가 있어, 단일 규칙에 한해 supported/contradicted/unobservable을 그대로 읽도록 보완했다. 설명 누락은 별도로 기록하고 여러 규칙에 대한 한 단어 응답은 전파하지 않는다. 내부 점검은 규칙별로 호출했다. 테스트 13개 통과. [명시적 판정 처리 기록]({prefix}/revisions/006_scalar_visual_verdict/verification.json).\n'
  body+='\n정상 규칙 확인 단계의 판정·설명 누락 집계: `'+json.dumps(profile.get('visual_check_counts',{}),ensure_ascii=False)+'`. 설명이 없는 명시적 판정에는 실행기가 보존한 원본 프레임 목록과 앞선 관찰을 연결하며, 시각적 이유를 새로 만들어 넣지 않았다.\n'
  if (out/'revisions/007_named_scalar_verdict/verification.json').exists():body+=f'\n내부 점검의 `N1: supported`처럼 ID와 판정만 명시된 응답도 설명 누락으로 구분하여 읽었다. 원문은 그대로이며 중복·잘못된 ID·모호한 판정은 실패로 남긴다. 테스트 14개 통과. [ID 포함 명시 판정 처리]({prefix}/revisions/007_named_scalar_verdict/verification.json).\n'
  if any(r['condition'].strip().lower()=='when applicable' for r in rules if r['accepted']):body+='\n채택된 규칙 중 적용 조건이 `when applicable`처럼 추상적인 항목이 있다. 근거 검사를 통과했다는 사실만으로 상세한 공정 단계 정의가 확보됐다고 해석하지 않는다. 이 제한을 유지한 동결 프롬프트의 효과를 기록한다.\n'
  if audit.get('summary_fallback_videos'):body+=f"\n요약 형식 복구를 소진한 정상 영상 **{len(audit['summary_fallback_videos'])}개**는 균등한 최대 6개 관찰 구간의 문장을 그대로 인용하는 고정 대체 절차를 사용했다. 영상 전체 관찰 원문은 보존했고, 이 표현은 모델이 생성한 JSON 요약이 아님을 명시했다. 독립 검사에서 문장·구간 위치가 원문과 정확히 일치함을 확인했다. [대체 처리 기록]({prefix}/summary_fallbacks.jsonl).\n"
  if (out/'revisions/002_unnamed_single_verdict/verification.json').exists():body+=f'\nR02 근거 응답은 단일 규칙에 대한 `supported | 설명` 형태였으나 ID 생략으로 거부됐다. 단일 규칙의 명시 판정·설명을 읽도록 보완하고 기존 원문을 재사용했다. 여러 규칙에 한 응답을 전파하지 않는다. [수정·재개 기록]({prefix}/revisions/002_unnamed_single_verdict/verification.json).\n'
  body+='\n실제 생성된 정상 설명:\n\n```text\n'+profile['normal_description'].rstrip()+'\n```\n\n실제 생성된 장면별 질문:\n\n```text\n'+profile['questions'].rstrip()+'\n```\n'
  body+=f'\n근거: [고정 설정]({prefix}/frozen.json), [입력 목록]({prefix}/input_manifest.json), [관찰 원문]({prefix}/observations), [후보와 규칙 판정]({prefix}/rules.json), [정상 설명·질문]({prefix}/normal_profile.json), [모든 호출]({prefix}/calls.jsonl), [독립 검산]({prefix}/independent_verification.json), [시간·VRAM]({prefix}/runtime_summary.json), [실행 로그](experiments/stage4/execution).\n'
 else:
  m=json.loads((out/'metrics.json').read_text());v=json.loads((out/'validation_metrics.json').read_text());counts=json.loads((out/'raw_prediction_counts.json').read_text());title=f'4단계 {scene} 독립 A/B/C 평가'
  row=f"| **4-{scene}-E** | **{scene} 정상 설명·질문 A/B/C 비교** | **완료** | AUROC A {m['A']['final']['auroc']:.2f} / B {m['B']['final']['auroc']:.2f} / C {m['C']['final']['auroc']:.2f}% |"
  body=f'''\n## 4단계 {scene} — A/B/C 평가 (완료)\n\n**{status['videos']}개 영상·{status['frames_per_condition']:,}프레임**의 동일 범위로 비교했다. A는 기존 Q0, B는 {scene} 정상 설명+Q0, C는 동일 정상 설명+{scene} 전용 질문이다. 설명·질문은 검증 전에 고정했고, 검증 결과에 따른 질문 선택·수정 없이 B/C를 모두 평가했다. A는 3단계 응답·점수를 재사용했으며 모든 점수를 재계산하여 일치를 확인했다. 질문과 무관한 기존 ImageBind 특징도 파일 해시·창·프레임 ID를 검증해 재사용했다.\n\n동결 InternVL2-8B BF16, seed 0, 결정적 생성, 16프레임 간격·30 FPS 가정·10초 창·8프레임 및 논문 기준 후처리는 동일하다. 정상 참조 이미지 추가나 수치 학습은 없다. 프레임 정답은 B/C 최종 추론이 모두 끝난 뒤 평가에만 사용했다.\n\n| 조건 | 최종 AUROC (%) | 최종 AP (%) | 초기 frame 이상 재현율 (%) | 초기 frame 정상 오탐률 (%) | 이상 판정 구간 / 전체 |\n|---|---:|---:|---:|---:|---:|\n'''
  for c in ['A','B','C']:
   x=m[c];co=counts[c];body+=f"| {c} | {x['final']['auroc']:.2f} | {x['final']['ap']:.2f} | {100*x['initial_binary']['recall']:.2f} | {100*x['initial_binary']['fpr']:.2f} | {sum(t['positive_segments'] for t in co.values())} / {sum(t['segments'] for t in co.values())} |\n"
  body+=f"\n주 비교 B−A AUROC **{m['B']['final']['auroc']-m['A']['final']['auroc']:+.2f}%p**, 보조 비교 C−B **{m['C']['final']['auroc']-m['B']['final']['auroc']:+.2f}%p**이다.\n\n| 점수 단계 | A AUROC / AP (%) | B AUROC / AP (%) | C AUROC / AP (%) |\n|---|---:|---:|---:|\n"
  for k in ['initial','retrieved','smoothed','final']:body+='| '+k+' | '+' | '.join(f"{m[c][k]['auroc']:.2f} / {m[c][k]['ap']:.2f}" for c in ['A','B','C'])+' |\n'
  body+='\n검증 영상의 분류 결과(질문 선택에 사용하지 않음):\n\n| 조건 | 정확도 (%) | TP / FP / TN / FN |\n|---|---:|---|\n'
  for c in ['A','B','C']:body+=f"| {c} | {100*v[c]['accuracy']:.2f} | {v[c]['tp']} / {v[c]['fp']} / {v[c]['tn']} / {v[c]['fn']} |\n"
  body+='\n재현율/오탐률은 초기 이진 점수를 원본 프레임에 확장한 값이다. 미세한 차이를 통계적 우월성으로 단정하지 않는다. 기존에 관찰한 IPAD 재분할의 탐색적 오프라인 비교이며, 미래 프레임·전체 영상 문맥을 사용한다. 모델 설명과 정상 규칙은 독립적인 사람 주석이 아니다.\n'
  body+=f'\n근거: [고정 조건]({prefix}/frozen.json), [B/C 실제 프롬프트]({prefix}/prompts.json), [원문 응답]({prefix}/inference), [전체 프레임 점수]({prefix}/frame_scores.csv), [전체 지표]({prefix}/metrics.json), [검증 지표]({prefix}/validation_metrics.json), [재사용 해시]({prefix}/reused_sources.json), [독립 검산]({prefix}/independent_verification.json), [시간·VRAM]({prefix}/runtime_summary.json), [실행 로그](experiments/stage4/execution).\n'
 text=re.sub(r'\*\*최신 완료:.*?\n',f'**최신 완료: {title}.** 아래에 해당 단계의 실제 결과와 근거를 기록했다.\n',text,count=1)
 position=text.index('\n\n진행 상태는');text=text[:position]+'\n'+row+text[position:];text+=body;path.write_text(text)
 registry[key]={'title':title,'status':'complete','execution_approved':True,'status_file':str((out/'status.json').relative_to(ROOT)),'artifact_directory':str(out.relative_to(ROOT))};registry_path.write_text(json.dumps(registry,ensure_ascii=False,indent=2)+'\n');print('Reported',key)
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--scene',required=True);p.add_argument('--kind',choices=['normal','evaluation'],required=True);a=p.parse_args();main(a.scene,a.kind)
